### ISSUE TITLE
Only define one Calender of many

### ISSUE THREAD

**Issue by aseedorf** [kristiantm/eink-family-calendar-esp32#2]
I have many Calendars and want to set up one E-Ink-Display for every calendar instead of displaying all calendars on one display.
How can i change "googleScript.gs" to use a specific calendar without the need of selecting this calendar.

Is the a possibility to enter the Name of teh Calendar e.g. "Room 2.10"?

Thank you, if there is an answer

**Comment by kristiantm** [comment]
Hi Aseedorf

If you look in the script code, it is possible to use this call below instead of the "get all calendars" call that I currently use.
CalendarApp.getCalendarsByName('NAME_OF_CALENDAR')[0]

I would experiment with that. If you want to control it from the endpoint, you could let it be a parameter of the call from the ESP device, and even add it as another saved parameter from the wifi-setup screen.

Best regards,
Kristian
